# Generated by Django 5.0.7 on 2024-08-07 17:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('rotina', models.CharField(max_length=80, verbose_name='Rotina')),
                ('inclusao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Incluir')),
                ('edicao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Editar')),
                ('exclusao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Excluir')),
                ('logs', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Logs')),
                ('filtro', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Filtro')),
                ('bloqueado', models.CharField(choices=[('B', 'Bloqueado'), ('L', 'Liberado')], max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('versao', models.CharField(max_length=3, verbose_name='Versão')),
                ('cliente', models.CharField(max_length=6, verbose_name='Cliente')),
                ('nomeCliente', models.CharField(max_length=80, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('pontual', 'Pontual'), ('sustentacao', 'Sustentação'), ('sd', 'Service Desk'), ('projeto', 'Projeto'), ('hradicional', 'Hora Adicional')], max_length=20, verbose_name='Tipo')),
                ('observacao', models.TextField(verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Senha')),
                ('password2', models.CharField(max_length=30, verbose_name='Confirmação da Senha')),
                ('bloqueado', models.CharField(choices=[('B', 'Bloqueado'), ('L', 'Liberado')], max_length=1, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('1', 'Colaborador'), ('2', 'Cliente')], max_length=1, verbose_name='Tipo')),
                ('perfil', models.CharField(choices=[('N1', 'Nivel 1'), ('N2', 'Nivel 2'), ('N3', 'Nivel 3'), ('N4', 'Nivel 4'), ('N5', 'Nivel 5')], max_length=3, verbose_name='Peril')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
