# Generated by Django 5.0.7 on 2024-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='comissao',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='% Desconto'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='imposto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='% Imposto'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='% Comissão'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='% Desconto'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='% Imposto'),
        ),
    ]
