# Generated by Django 5.0.7 on 2024-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
