# Generated by Django 5.0.7 on 2024-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Registro ativo ?')),
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor Hora')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor Fixo')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='% Comissão')),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='% Imposto')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='% Desconto')),
                ('observacao', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name_plural': 'Valores',
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
