# Generated by Django 5.0.7 on 2024-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projetos_valor_hora_alter_projetos_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
