# Generated by Django 5.0.7 on 2024-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_servicos_base_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='comissao',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='% Comissão'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='horas_especificacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas Especificação'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='R$ Liquido'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='R$ Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='R$ Valor Comissao'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='R$ Valor Recebido'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='% Comissão'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='% Desconto'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='imposto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='% Imposto'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Valor Fixo'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Valor Hora'),
        ),
    ]
