# Generated by Django 5.0.7 on 2024-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_usuario_username_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usefilter',
            field=models.BooleanField(default=True),
        ),
    ]
