# Generated by Django 5.0.7 on 2024-08-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projetos_data_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='qtd_horas_apontadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='qtd_horas_projeto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
