# Generated by Django 5.0.7 on 2024-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_usuario_usefilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bloqueado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Usuário ativo ?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='resetpsw',
            field=models.BooleanField(default=True, verbose_name='Altera Senha ?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usefilter',
            field=models.BooleanField(default=True, verbose_name='Permite o uso de Filtros ?'),
        ),
    ]
