# Generated by Django 5.0.7 on 2024-09-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_colaborador_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='perc_desconto_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='% Desconto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_hora_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor Hora'),
        ),
    ]
