# Generated by Django 5.0.7 on 2024-08-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_usuario_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Descrição')),
                ('cnpj', models.CharField(choices=[('F', 'Pessoa Fisica'), ('J', 'Pessoa Juridica')], max_length=14, verbose_name='CNPJ')),
                ('valor_hora_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perc_desconto_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
