# Generated by Django 5.0.7 on 2024-08-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_usuario_bloqueado_usuario_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveis',
            old_name='bloqueado',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='active',
        ),
    ]
