# Generated by Django 5.0.7 on 2024-09-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_cliente_perc_desconto_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('item', models.CharField(max_length=5, verbose_name='Item')),
                ('descricao_item', models.CharField(max_length=200, verbose_name='Descrição')),
                ('sub_item', models.CharField(max_length=5, verbose_name='Sub-Item')),
                ('descricao_sub_item', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('Protheus', 'Protheus'), ('Processo', 'Processo'), ('ADVPL', 'ADVPL'), ('Qualidade', 'Qualidade'), ('Outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas')),
                ('save', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Save')),
                ('execaucao', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Execução')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.servicos')),
            ],
            options={
                'verbose_name_plural': 'Itens Serviços',
            },
        ),
    ]
