# Generated by Django 5.0.7 on 2024-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_bloqueado_niveis_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveis',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Nível ativo ?'),
        ),
    ]
