# Generated by Django 5.0.7 on 2024-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_empresa_options_remove_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveis',
            options={'ordering': ('nivel_id', 'descricao'), 'verbose_name_plural': 'Niveis'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contatos',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contatos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dados_bancarios',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Informações Bancárias'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cat',
            field=models.CharField(default='', max_length=100, verbose_name='E-mail Cat'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, verbose_name='Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ie',
            field=models.CharField(blank=True, max_length=14, verbose_name='IE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usa_email_cat',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='', max_length=1, verbose_name='Recebe E-mail Cat?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perc_desconto_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_hora_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='Estado'),
        ),
    ]
