# Generated by Django 5.0.7 on 2024-09-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_itemservico_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemservico',
            old_name='execaucao',
            new_name='execucao',
        ),
    ]
