# Generated by Django 5.0.7 on 2024-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_niveis_options_rename_name_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Cliente ativo ?'),
        ),
    ]
