# Generated by Django 5.0.7 on 2024-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_execaucao_itemservico_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='niveis',
            name='rotina',
            field=models.CharField(choices=[('0', 'Todas'), ('1', 'Empresas'), ('2', 'Niveis'), ('3', 'Usuários'), ('4', 'Serviços')], max_length=80, verbose_name='Rotina'),
        ),
        migrations.DeleteModel(
            name='Projetos',
        ),
    ]
