# Generated by Django 5.0.7 on 2024-09-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_cliente_cnpj_alter_niveis_rotina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
    ]
