# Generated by Django 5.0.7 on 2024-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_cliente_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default='', max_length=80, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade'),
        ),
    ]
