# Generated by Django 5.0.7 on 2024-09-01 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_servicos_nomecliente_alter_cliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.cliente'),
        ),
    ]
