# Generated by Django 5.0.7 on 2024-09-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_colaborador_cep_colaborador_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='periodo_lancamento',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Periodo Lancto'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(default='', max_length=14, verbose_name='Telefone'),
        ),
    ]
