# Generated by Django 5.0.7 on 2024-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_colaborador_periodo_lancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
