# Generated by Django 5.0.7 on 2024-09-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_valores_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='parcelamento',
        ),
        migrations.AddField(
            model_name='servicos',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd Parcelas'),
        ),
    ]
