# Generated by Django 5.0.7 on 2024-09-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_servicos_parcelamento_servicos_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='versao_valida',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Versão Valida'),
        ),
    ]
