# Generated by Django 5.0.7 on 2024-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_grupos_alter_usuario_perfil_itemgrupo_delete_niveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgrupo',
            name='rotina',
            field=models.CharField(choices=[('1', 'Empresas'), ('2', 'Grupos'), ('3', 'Usuários'), ('4', 'Serviços')], max_length=80, verbose_name='Rotina'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd Parcelas'),
        ),
    ]
