# Generated by Django 5.0.7 on 2024-10-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_itemgrupo_item_grupo_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'ordering': ('codigo', 'descricao'), 'verbose_name_plural': 'Grupos de Acesso'},
        ),
        migrations.RenameField(
            model_name='grupos',
            old_name='grupo_id',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='itemgrupo',
            old_name='item_grupo_id',
            new_name='grupo',
        ),
    ]
